name: networkx
channels:
- defaults
dependencies:
- python=3.6
- matplotlib
- scipy
- numpy
- jupyter
- jupyterlab
- ipykernel
- pandas

- pip:
    - environment_kernels
    - ndlib
    - networkx=2.0b2
